[workspace]
resolver = "2"
members = [
    "crates/mus-notation",
    "crates/mus-oplog",
    "crates/mus-graph",
    "crates/mus-text",
    "crates/mus-engine",
    "crates/mus-cli",
    "crates/mus-vocab",
    "crates/mus-dsp",
    "crates/np-rand",
]

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/sophia-labs/mus"
